# Generated by Django 6.0 on 2025-12-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_word', models.CharField(max_length=100, unique=True, verbose_name='错误词语')),
                ('correct_word', models.CharField(max_length=100, verbose_name='正确词语')),
            ],
        ),
    ]
