# Generated by Django 6.0 on 2026-01-03 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='员工姓名')),
                ('gender', models.CharField(choices=[(1, '男'), (2, '女')], max_length=10, verbose_name='员工性别')),
                ('age', models.IntegerField(verbose_name='员工年龄')),
                ('account', models.CharField(default='0', max_length=10, verbose_name='员工账号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.departments', verbose_name='部门')),
            ],
        ),
    ]
