# Generated by Django 6.0 on 2026-01-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='create_time',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
    ]
