# Generated by Django 6.0 on 2026-01-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_alter_employees_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='lianghao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('price', models.IntegerField(verbose_name='价格')),
                ('level', models.SmallIntegerField(choices=[(1, '一级'), (2, '二级'), (3, '三级')], verbose_name='等级')),
                ('status', models.CharField(choices=[(1, '未占用'), (2, '已占用')], default=2, max_length=10, verbose_name='状态')),
            ],
        ),
    ]
