# Generated by Django 6.0 on 2026-01-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_lianghao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lianghao',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '未占用'), (2, '已占用')], default=2, verbose_name='状态'),
        ),
    ]
