# Generated by Django 6.0 on 2026-01-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_alter_lianghao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lianghao',
            name='status',
            field=models.SmallIntegerField(blank=True, choices=[(1, '未占用'), (2, '已占用')], default=2, null=True, verbose_name='状态'),
        ),
    ]
