# Generated by Django 6.0 on 2026-01-04 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0007_alter_lianghao_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lianghao',
            name='status',
        ),
    ]
