# Generated by Django 6.0 on 2026-01-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_remove_lianghao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lianghao',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '未占用'), (2, '已占用')], default=1, verbose_name='状态'),
        ),
    ]
