# Generated by Django 6.0 on 2026-01-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0010_remove_lianghao_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lianghao',
        ),
    ]
