# Generated by Django 6.0 on 2026-01-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0012_lianghao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (2, '女')], verbose_name='员工性别'),
        ),
    ]
