# Generated by Django 6.0 on 2026-01-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0013_alter_employees_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
            ],
        ),
    ]
